application: go4free
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheet
  static_dir: stylesheet

- url: /images
  static_dir: images
  
- url: .*
  script: go4free.app

libraries:
- name: jinja2
  version: "latest"
- name: webapp2
  version: "2.5.2"
